// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSjwx7ARMh2rT47hji3g1mKFi-C8pMChA',
    appId: '1:294005036435:web:a36e96a6b761e11690c466',
    messagingSenderId: '294005036435',
    projectId: 'heliosa-firebas',
    authDomain: 'heliosa-firebas.firebaseapp.com',
    storageBucket: 'heliosa-firebas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmAtaqTnpr2RntWkX_9Fk_I2dY3kyrr2A',
    appId: '1:294005036435:android:b4591e568d91ae4890c466',
    messagingSenderId: '294005036435',
    projectId: 'heliosa-firebas',
    storageBucket: 'heliosa-firebas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3VbzFSM3ql_OtH671rQKKnokNtIeT5iY',
    appId: '1:294005036435:ios:02291a512cb9867c90c466',
    messagingSenderId: '294005036435',
    projectId: 'heliosa-firebas',
    storageBucket: 'heliosa-firebas.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3VbzFSM3ql_OtH671rQKKnokNtIeT5iY',
    appId: '1:294005036435:ios:02291a512cb9867c90c466',
    messagingSenderId: '294005036435',
    projectId: 'heliosa-firebas',
    storageBucket: 'heliosa-firebas.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
